name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Validate YAML syntax
        run: |
          echo "Validating YAML..."
          yamllint -d '{
            extends: default,
            rules: {
              document-start: disable,
              line-length: disable,
              truthy: disable,
              new-line-at-end-of-file: disable
            }
          }' .